### ISSUE TITLE
[Others]: macOS版本并没有按照计划推出

### ISSUE THREAD

**Issue by VinsonFather** [SlopeCraft/SlopeCraft#100]
### Description

怎么还不更新macOS的呀，我一个用Mac的很憋屈啊。

**Comment by Cubik65536** [comment]
> ### Description
> 怎么还不更新macOS的呀，我一个用Mac的很憋屈啊。

因为一些兼容原因我们暂时不能在 macOS 上编译程序，需要等 @ToKiNoBug 修复一下，暂时建议使用虚拟机+没有 AVX 要求的 SlopeCraft 版本

**Comment by ToKiNoBug** [comment]
目前已经更新了macos的二进制，但由于技术问题，用户需要先安装homebrew和qt。建议访问[homebrew官网](https://brew.sh/)安装homebrew，执行`brew install qt@6`来安装qt
