### ISSUE TITLE
[Bug]: 导出的平面地图画中有部分区块缺失

### ISSUE THREAD

**Issue by TheFairyTale** [SlopeCraft/SlopeCraft#102]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

当我在正常导出Litematica 格式的地图画后，在1.20.1 的Fabric （版本0.87.0）的litematica投影mod（版本0.15.3） 中加载该原理图后发现，地图画的大部分区块都可正常载入，但部分区块缺失
![image](https://github.com/SlopeCraft/SlopeCraft/assets/16740355/a31ee95d-d7a2-473f-83e9-36b5f0fa4515)

这是导入的litematica 投影文件(下载后将其.zip 后缀名称改为.litematic)：
[640x360_EC40E90D4FBE428D06E712F79B055D40.zip](https://github.com/SlopeCraft/SlopeCraft/files/12803992/640x360_EC40E90D4FBE428D06E712F79B055D40.zip)

### 重现

1.在“地图画配置”选项卡中，游戏版本选1.20，地图画类型选择“平板地图画”，并在右侧的方块列表预设附近找到并点按“优先羊毛”
![image](https://github.com/SlopeCraft/SlopeCraft/assets/16740355/d8d496e1-7f61-47ad-9902-fae70c92405f)

2.在“导入图像并转化”选项卡中，在左边栏点击“添加”，添加一张长640宽360的JPEG图片，然后在中间栏点击转化后，再在右边栏的“转化算法”选择"Lab00"并勾选 “抖动”，然后点击转化当前图像，等待进度条加载到100%后
![image](https://github.com/SlopeCraft/SlopeCraft/assets/16740355/608bd365-a808-4483-8f40-21d25bc9889f)

3. 切换到“导出选项卡”，在左侧“项目池”中选择刚刚转换的图像，在靠上部分选择Litematica 单选框，投影名称输入“CouELingDiTuHua”，投影区域名称留空，压缩高度勾选“无损压缩”，不勾选搭桥，勾选“防火”、“防末影人”、 “连接蘑菇块”三个复选框，然后在右下角点按“预购建三维结构”，然后点按“全部导出”，将投影文件导出到Minecraft 的schematics 文件夹中。
![image](https://github.com/SlopeCraft/SlopeCraft/assets/16740355/013876f9-0ff4-4a33-b3b6-4679a90b101b)

4. 启动带有Fabric 及litematica 投影mod的Minecraft 版本，在新创建的超平坦世界中摁“M”(默认键位是M)打开投影菜单，选择“加载原理图”，然后点击一下刚刚导出的投影文件的名称，点击左下角的“加载原理图”按钮，等待游戏将原理图加载至世界中，最后观察整张平面地图画，可发现部分区块的地图画是缺失的。

### 环境

- **操作系统**：Windows 11 家庭中文版 22H2
- **SlopeCraft 版本：5.2.0
Java ： JDK 17.0.3.1
Minecraft: 1.20.1
Fabric Api : 0.87.0
litematica: 0.15.3 (目前curseforge 最新测试版本)
malilib (投影模组前置): 0.16.2

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by TheFairyTale** [comment]
这是“复现”一节，第二步骤中被转为地图画的图片：
![640x360_EC40E90D4FBE428D06E712F79B055D40](https://github.com/SlopeCraft/SlopeCraft/assets/16740355/dcd5e7ec-5f6b-4404-b71d-cbfb398b0718)

**Comment by ToKiNoBug** [comment]
等待足够长的时间之后，也是这样吗？请提供一下输出的litematica文件

**Comment by ToKiNoBug** [comment]
我试了一下，这应该是litematica的bug，因为我按f3+M刷新投影显示之后就一切正常了，黏贴原理图也是完整的。（以上都是使用你提供的litematica文件测试的结果。建议多F3+M

**Comment by TheFairyTale** [comment]
> 我试了一下，这应该是litematica的bug，因为我按f3+M刷新投影显示之后就一切正常了，黏贴原理图也是完整的。（以上都是使用你提供的litematica文件测试的结果。建议多F3+M

好的，我这边按照您提供的方式重试了下，确实可以正常渲染了，感谢解答，辛苦了！
