### ISSUE TITLE
[Others]: GitHub Action compiled binary for macOS not working.

### ISSUE THREAD

**Issue by Cubik65536** [SlopeCraft/SlopeCraft#104]
### Description

The binaries for macOS compiled with GitHub Action doesn't work because the dylibs are incorrectly processed (it would cause an immediate crash after start).

**Comment by ToKiNoBug** [comment]
x64 or apple silicon?

**Comment by Cubik65536** [comment]
> x64 or apple silicon?

both, I’ll take in charge of this

**Comment by ToKiNoBug** [comment]
> > x64 or apple silicon?
> 
> both, I’ll take in charge of this

Probably because qt is not deployed?
