### ISSUE TITLE
[Bug]: 地图画起始序号无法输入大于99的数字/Cannot enter any number larger than 99 as the start number of map file

### ISSUE THREAD

**Issue by berylliumcopper** [SlopeCraft/SlopeCraft#106]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

当我选择“游戏版本：1.19”、“地图画类型：纯文件地图画”，然后导入图像转化为地图画后：
在“导出-地图文件”页面更改“地图画起始序号”时，只能输入0到99之间的数字。
并且，如果在数字为99时按数字右上角的增加键（上键），数字不会变为100，而是仍然为99。
![屏幕截图 2023-11-11 125718](https://github.com/SlopeCraft/SlopeCraft/assets/63218389/8dbfa4ae-efcf-4258-8f23-5f6a31cf5c60)

### 重现

1.从Release下载5.2.0版本
2.在“地图画配置”中选择“纯文件地图画”
3.导入一张png图片并转化成地图画
4.在”导出“中选择”地图文件“：(1)在”地图画起始序号“中试图输入一个大于99的数字，发现只有前两位数可以成功输入。(2)在”地图画起始序号“中输入99，再点击其右边的增加编号按钮，发现序号并没有增加到100。

### 环境

- **操作系统**：Windows 11 家庭中文版 22H2
- **SlopeCraft 版本：**：5.2.0

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by berylliumcopper** [comment]
十分感谢！

**Comment by ToKiNoBug** [comment]
已经修复，请查看最新的release：https://github.com/SlopeCraft/SlopeCraft/releases/tag/v5.2.1
