### ISSUE TITLE
[Bug]: 可再生方块被错误标记

### ISSUE THREAD

**Issue by HarukaB** [SlopeCraft/SlopeCraft#108]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

在VisualCraft中，灵魂沙，滴水石块，磨制闪长岩，磨制花岗岩，黏土，末地石，下界砖被标记为“不可再生“，但灵魂沙实际上在下界更新加入猪灵交易后就已经是可再生资源，滴水石块/磨制安山岩，闪长岩，花岗岩可以通过与老手石匠村民交易获取。
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/100848181/b71f2458-37ea-4407-b219-9067cb877187)
粘土可以通过将泥巴放置在下方挂有滴水石锥的方块上方来再生。
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/100848181/0da5897d-eb10-4998-a77a-8b2547c3118d)
末地石可以通过重生/杀死末影龙再生，末地石砖由于末地石可再生自然也是可再生资源。
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/100848181/8b063da8-02d9-4299-a6bb-0250f98fe7c1)
下界砖可以通过猪灵交易来获取，从而使下界砖块可再生成为可能。
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/100848181/ded42216-8638-4f0e-83ab-14837137d289)

### 重现

1.从release下载应用，打开visualcraft
2.在"基础属性"选项卡中选择1.20游戏版本，然后在工具栏中点击资源-->加载资源，然后在"方块列表"选项卡内点击"全部启用"，然后点击"禁用不可再生"
3.发现可再生的资源实际上并没有被启用

### 环境

- **操作系统**：Windows 11 23H2 ，macOS Sonoma 14.3 (均进行了测试)
- **SlopeCraft 版本**：均为5.2.1：

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by HarukaB** [comment]
另外，不知道是不是Bug，好像石类方块的列表里没有磨制安山岩

**Comment by HarukaB** [comment]
都是按照最新版本测试的，由于我不太清楚VCL_blocks_fixed.json的具体格式，以及对不同版本该如何处理，就暂时没有开修复的pr

**Comment by ToKiNoBug** [comment]
感谢反馈，我会修正这些错误
