### ISSUE TITLE
[Bug]: 无法导入jpg图像

### ISSUE THREAD

**Issue by Mifan-T** [SlopeCraft/SlopeCraft#109]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

随意导入一张jpg格式的图片，会弹出下述错误信息：
![image](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/eb3d94f2-533a-4f6a-9063-ba244f596244)
- 经测试不是图像尺寸导致的，任何jpg图像都无法导入
- png图像可以正常导入，原先无法导入的jpg转换为png后也可以导入
- 这是5.2.2的新bug，上个版本是正常的

#### 吐槽：

*（另外吐槽一个点：SlopeCraft的多核优化看起来挺好？导入图片的时候几乎吃满了所有核😂）*
![image](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/e369ef79-93e6-4083-8691-6b45c16b8f85)

### 重现

无论什么步骤都能100%复现（至少我电脑上是如此）

### 相关日志输出（如果有）

```Shell
打开图像失败无法打开图像D:/主文件夹/工作台/SlopeCraft修修修修修bug/导入用图片/斯卡蒂-线性384.jpg。常见原因:图像尺寸太大.详细信息:加载图片D:/主文件夹/工作台/SlopeCraft修修修修修bug/导入用图片/斯卡蒂-线性384.jpg 失败。
```

### 环境

- **操作系统**：Windows 10 专业版 21H1
- **SlopeCraft 版本：**：5.2.2

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by Cubik65536** [comment]
@Mifan-T 请为 issue 添加标题

**Comment by Cubik65536** [comment]
macOS 版本无法复现问题，大概不是跨平台问题，要是 @ToKiNoBug 短时间内没测其他平台我有时间会去测 Windows 的

**Comment by ToKiNoBug** [comment]
我已经在windows上复现了这个问题，正在修复

**Comment by ToKiNoBug** [comment]
搞明白问题了，我升级了一下windows上用的qt版本（从6.5.0升到6.6.2），但我用的6.6.2版本是自己编译的，漏了imageformats插件，导致不能读取jpg图片。现在修复这个bug，用新的压缩包替换了release上出错的压缩包。windows上novec nogpu的版本应该没有这个问题。

**Comment by Mifan-T** [comment]
@ToKiNoBug 
说个很尴尬的事情，我下载了最新的压缩包，但仍然无法导入任何的jpg文件（我才发现的😂）

![image](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/f9ccc516-419f-4c31-ba63-1f440cdadcc8)

不过 `SlopeCraft-5.2.2-win64-novec-nogpu` 版本倒是确实能正常导入

**Comment by ToKiNoBug** [comment]
> @ToKiNoBug 说个很尴尬的事情，我下载了最新的压缩包，但仍然无法导入任何的jpg文件（我才发现的😂）
> 
> ![image](https://private-user-images.githubusercontent.com/49829769/320069516-f9ccc516-419f-4c31-ba63-1f440cdadcc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODQyNTMsIm5iZiI6MTcxMjM4Mzk1MywicGF0aCI6Ii80OTgyOTc2OS8zMjAwNjk1MTYtZjljY2M1MTYtNDE5Zi00YzMxLWJhNjMtMWY0NDBjZGFkY2M4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA2MTIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZTE5ODEzYWEwOGUyOTI2ZjAxNjUzYjgzNDcyZmEwZTk0ZDQ5MzhmNzgyY2Y2MjQwZjY4YWY2ZDVkZTE5NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ygx9ICFq5Ohat4H3-eAPbZRnIeIPLpTtHVLjyMOl890)
> 
> 不过 `SlopeCraft-5.2.2-win64-novec-nogpu` 版本倒是确实能正常导入

已经上传了一个新的压缩包，现在它可以导入了
