### ISSUE TITLE
[特性]: 导出的平面示意图不带数字标记

### ISSUE THREAD

**Issue by Mifan-T** [SlopeCraft/SlopeCraft#110]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

从5.1.0版本开始，SlopeCraft导出的平面示意图就不带数字标记了
|      5.0.1               |          5.1.0          |
|:------------------:|:------------------:|
| ![QR](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/5c218466-bb08-4edd-ac80-955528426640) | ![QR flat-diagram](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/4300658f-cbde-4294-b71c-7ad02d320767) |

我不清楚这是bug还是特意为之

*ps：因为最近在写教程，所以遇到了各种神奇的“特性”*，有点尴尬的说（

### 重现

几乎全使用默认设置进行导出

### 环境

- **操作系统**：Windows 10 专业版 21H1
- **SlopeCraft 版本：**：5.0.1/5.1.0

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by ToKiNoBug** [comment]
是的，这是重构一部分代码时候去掉的，我觉得有区块分隔线已经足够了
