### ISSUE TITLE
[Bug]: 启用有损压缩后，无法预览压缩效果

### ISSUE THREAD

**Issue by OctaAcid** [SlopeCraft/SlopeCraft#113]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

当勾选“无损压缩”和“有损压缩”以限制像素画高度时，预构建三维结构后无法预览材料表和压缩效果。提示“尚未构建三维结构”。
但是，投影文件可以正常导出和使用。这使我无法方便地判断导出的文件相比在图像转化阶段得到的图像有哪些区别。
https://github.com/SlopeCraft/SlopeCraft/assets/109903914/464c84c2-7233-438d-bd90-712460867e61

### 重现

我使用了一张128*250的图片进行生成，并尝试将高度压缩到32格。在RGB+域进行转化，包含抖动，在导出界面设置最大允许高度，勾选无损压缩和有损压缩，预生成三维结构，随后在尝试预览时遇到了这个bug。事实上，任何尝试让有损压缩参与处理的生成都能触发这个bug。

### 环境

- **操作系统**：Windows 10 22H2
- **SlopeCraft 版本：**：5.2.2

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by OctaAcid** [comment]
是否可以考虑显示未更新的预览信息交给用户自行判断

**Comment by ToKiNoBug** [comment]
我重复不出这个bug，在我的电脑上，一切正常。这可能是因为你的用户名包含非ascii字符，而我没有处理好这种情况，我会尝试解决一下。
这是因为SlopeCraft的缓存位于`C:/Users/<用户名>/AppData/Local/Temp/SlopeCraft`，用户名里的非ascii字符会造成非常经典的乱码问题，我相信如果换一个纯英文的用户重试这个操作，应该不会出现这个bug。

**Comment by OctaAcid** [comment]
新用户没有解决这个问题。另外，当有损压缩不工作时（不启用或高度限制高于实际高度），这个bug不会出现。无损压缩可以正常工作，它将116高度的图片压缩到了109高度，并给出了材料列表。希望这些信息能够有用。

**Comment by Mifan-T** [comment]
emm我倒是发现一个神奇的问题

我导入以下图像，使用RGB+算法转化，在导出界面尝试使用无损压缩和有损压缩，并预构建三维结构

![斯卡蒂-立方512](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/1ff4e9ea-decf-4d97-991c-99db0d30ff4a)

结果非常奇怪，使用无损压缩时结构大小为514×123×514，而使用有损压缩时结构大小为514×257×514，这很明显是不符合预期的

|      无损压缩               |          有损压缩          |
|:------------------:|:------------------:|
| ![image](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/86b1c170-d6c2-4781-b9cd-67b9824ff1de) | ![image](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/736d53c0-073f-483d-a51b-813837476c98) |

使用版本：`SlopeCraft-5.2.2-win64-novec-nogpu`（普通版本貌似还有bug，没法导入jpg）

**Comment by ToKiNoBug** [comment]
> emm我倒是发现一个神奇的问题
> 
> 我导入以下图像，使用RGB+算法转化，在导出界面尝试使用无损压缩和有损压缩，并预构建三维结构
> 
> ![斯卡蒂-立方512](https://private-user-images.githubusercontent.com/49829769/320096008-1ff4e9ea-decf-4d97-991c-99db0d30ff4a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODEwMDMsIm5iZiI6MTcxMjM4MDcwMywicGF0aCI6Ii80OTgyOTc2OS8zMjAwOTYwMDgtMWZmNGU5ZWEtZGVjZi00ZDk3LTk5MWMtOTlkYjBkMzBmZjRhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1MTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NWJlM2U4ZTI3MjBkMzk2MTM2NTdhODc0NGQzNjJmYzhhYjA3ZmIyMmRlYTNjYWVlY2I4MGQ3MTQwZGUzZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_IiuKx6O_jmS06sgUodp9BKDczHK5iUjyTy6jK_zws)
> 
> 结果非常奇怪，使用无损压缩时结构大小为514×123×514，而使用有损压缩时结构大小为514×257×514，这很明显是不符合预期的
> 无损压缩 	有损压缩
> ![image](https://private-user-images.githubusercontent.com/49829769/320097351-86b1c170-d6c2-4781-b9cd-67b9824ff1de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODEwMDMsIm5iZiI6MTcxMjM4MDcwMywicGF0aCI6Ii80OTgyOTc2OS8zMjAwOTczNTEtODZiMWMxNzAtZDZjMi00NzgxLWI5Y2QtNjdiOTgyNGZmMWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1MTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYzcxZDRkNTgzMjYxYmE3MjdiOWNjMmM1NDIyNjQ4ZTM1ZjkxNTM0NzdiODMxMGQ0ZTNkMGE2NmM5NjgwODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vrg6xN2ByJGdN6DtNj1-giyRd6oN4rmXj8qCCT8uDnU) 	![image](https://private-user-images.githubusercontent.com/49829769/320097449-736d53c0-073f-483d-a51b-813837476c98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODEwMDMsIm5iZiI6MTcxMjM4MDcwMywicGF0aCI6Ii80OTgyOTc2OS8zMjAwOTc0NDktNzM2ZDUzYzAtMDczZi00ODNkLWE1MWItODEzODM3NDc2Yzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1MTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NmI2ZWQ0NmU4M2FlYzhiY2U3ZjE0YzQzMGE0YTE3MDdkYmRjMzY1MzZiODc0NjdiMzE1NDM5ZTE4NDAwMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZrhZFofgehivz0kPm3S7ApmXkjyIUyxzE9E0sVxDRgs)
> 
> 所以，有没有一种可能，有损压缩并没有按预期方式工作？
> 
> 使用版本：`SlopeCraft-5.2.2-win64-novec-nogpu`（普通版本貌似还有bug，没法导入jpg）

emmmmmm，有损压缩应该没有出错，只是你完全可以同时勾选有损和无损。

**Comment by ToKiNoBug** [comment]
> > emm我倒是发现一个神奇的问题
> > 我导入以下图像，使用RGB+算法转化，在导出界面尝试使用无损压缩和有损压缩，并预构建三维结构
> > ![斯卡蒂-立方512](https://private-user-images.githubusercontent.com/49829769/320096008-1ff4e9ea-decf-4d97-991c-99db0d30ff4a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODEwMDMsIm5iZiI6MTcxMjM4MDcwMywicGF0aCI6Ii80OTgyOTc2OS8zMjAwOTYwMDgtMWZmNGU5ZWEtZGVjZi00ZDk3LTk5MWMtOTlkYjBkMzBmZjRhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1MTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NWJlM2U4ZTI3MjBkMzk2MTM2NTdhODc0NGQzNjJmYzhhYjA3ZmIyMmRlYTNjYWVlY2I4MGQ3MTQwZGUzZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_IiuKx6O_jmS06sgUodp9BKDczHK5iUjyTy6jK_zws)
> > 结果非常奇怪，使用无损压缩时结构大小为514×123×514，而使用有损压缩时结构大小为514×257×514，这很明显是不符合预期的
> > 无损压缩 	有损压缩
> > ![image](https://private-user-images.githubusercontent.com/49829769/320097351-86b1c170-d6c2-4781-b9cd-67b9824ff1de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODEwMDMsIm5iZiI6MTcxMjM4MDcwMywicGF0aCI6Ii80OTgyOTc2OS8zMjAwOTczNTEtODZiMWMxNzAtZDZjMi00NzgxLWI5Y2QtNjdiOTgyNGZmMWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1MTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYzcxZDRkNTgzMjYxYmE3MjdiOWNjMmM1NDIyNjQ4ZTM1ZjkxNTM0NzdiODMxMGQ0ZTNkMGE2NmM5NjgwODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vrg6xN2ByJGdN6DtNj1-giyRd6oN4rmXj8qCCT8uDnU) 	![image](https://private-user-images.githubusercontent.com/49829769/320097449-736d53c0-073f-483d-a51b-813837476c98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODEwMDMsIm5iZiI6MTcxMjM4MDcwMywicGF0aCI6Ii80OTgyOTc2OS8zMjAwOTc0NDktNzM2ZDUzYzAtMDczZi00ODNkLWE1MWItODEzODM3NDc2Yzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA1MTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NmI2ZWQ0NmU4M2FlYzhiY2U3ZjE0YzQzMGE0YTE3MDdkYmRjMzY1MzZiODc0NjdiMzE1NDM5ZTE4NDAwMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZrhZFofgehivz0kPm3S7ApmXkjyIUyxzE9E0sVxDRgs)
> > 所以，有没有一种可能，有损压缩并没有按预期方式工作？
> > 使用版本：`SlopeCraft-5.2.2-win64-novec-nogpu`（普通版本貌似还有bug，没法导入jpg）
> 
> emmmmmm，有损压缩看来是有些问题的，方块高度超出限高了。但是这个问题不严重，你完全可以同时勾选有损和无损，这两种压缩方式不互斥。

**Comment by ToKiNoBug** [comment]
我重复了几遍，我确认启动有损压缩会导致没法预览压缩效果和材料表……这个软件已经有很多过时的设计，是时候局部重构一下了

**Comment by ToKiNoBug** [comment]
5.3.0已修复
