### ISSUE TITLE
[Bug]: `地图画配置` 中未勾选基础颜色 Stone 时导出结果仍出现相关方块

### ISSUE THREAD

**Issue by Tinhone** [SlopeCraft/SlopeCraft#115]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

如题，当我在 `地图画配置` 一栏中未勾选基础颜色 Stone 时，导出结果仍会出现相关方块。

另外，我尝试查看[最新的构建](https://github.com/SlopeCraft/SlopeCraft/actions/runs/8867332385)（SlopeCraft-dev-3042257-Release-None-vec=true-windows-clang-7z）是否存在此问题，但启动时遇到了致命报错，若需要可开新 Issue：
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/c7f34b8d-cd67-483e-94ef-6fe53a47af4e)

另外的另外，启动 Release v5.2.2 时还会弹出警告，日志是空的，若需要可开新 Issue：
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/8cb31169-5fd5-4307-9855-ac6e3f4dcd39)

### 重现

1. 从 Release 下载应用 [SlopeCraft-5.2.2-win64.7z](https://github.com/SlopeCraft/SlopeCraft/releases/download/v5.2.2/SlopeCraft-5.2.2-win64.7z)
2. 修改 CustomBlocks.json（附件 1）
3. 进入 `地图画配置` 一栏，以图示内容（附件 2）设置，再加载预设（附件 3），其他未修改。这里需注意设置顺序，否则自定义预设会被覆盖（也许可以优化一下）
4. 切换至 `导入图像并转化` 一栏，导入图像（附件 4）并以图示内容（附件 5）设置，自定义背景色为 `#000000`，其他未修改，选择图像后点击 `转化当前图像`
5. 切换至 `导出` 一栏，选择图像后点击 `预构建三维结构`，点击 `预览材料表`，发现图示内容（附件 6）

附件 1：[CustomBlocks.json](https://github.com/SlopeCraft/SlopeCraft/files/15299259/CustomBlocks.json)
附件 2：[图片](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/9741bc7b-b59e-4217-8b0b-d517ac8b8740)
附件 3：[单色期望.zip](https://github.com/SlopeCraft/SlopeCraft/files/15299136/default.zip)
附件 4：[Report](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/cbc6bef2-90fc-4e99-badf-a57f1dd28f5e)
附件 5：[图片](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/6bd1ec39-fcb3-47b3-8fa9-0696f5943f14)
附件 6：[图片](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/03271bfd-d5d2-45d9-ab9b-02a928150518)

### 环境

- **操作系统**：Windows 10 22H2
- **SlopeCraft 版本：**：5.2.2

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by Mifan-T** [comment]
已复现，投影材料表如下
![image](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/76a69b75-e0e2-4e41-822b-23688fae22be)

不过这只是上方的平滑石头边框，属于正常情况，不会影响成品地图

![image](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/126ad78b-1ca2-4384-8230-4d0c1e01fc7e)

**Comment by Mifan-T** [comment]
不过我发现了另一个问题：导出的平面示意图是使用方块的平视图生成的，这导致平视图和俯视图不同的方块的效果很奇怪。

特别是上述步骤导出的平面示意图，可以说是很诡异了
![Report flat-diagram](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/1b505431-a352-4552-a8ab-c2f60047ce55)

**Comment by Mifan-T** [comment]
> 不过我发现了另一个问题：导出的平面示意图是使用方块的侧视图生成的，这导致侧视图和俯视图不同的方块的效果很奇怪。
> 
> 特别是上述步骤导出的平面示意图，可以说是很诡异了 ![Report flat-diagram](https://private-user-images.githubusercontent.com/49829769/330205306-1b505431-a352-4552-a8ab-c2f60047ce55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MzQ4MjEsIm5iZiI6MTcxNTYzNDUyMSwicGF0aCI6Ii80OTgyOTc2OS8zMzAyMDUzMDYtMWI1MDU0MzEtYTM1Mi00NTUyLWE4YWItYzJmNjAwNDdjZTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDIxMDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3N2IzNmY1MWUxNDliM2NiMWM4Zjc1NzY3NjBkMTBlNWJmYzY5ODYwODRlZThlMDMzNTAxNjYxMDhlN2ZiYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a18odMYfQQrl6ndSSfvQsBDuRyGgZOiSXOwfQE-5C00)

**Comment by Cubik65536** [comment]
> 顺便也补充下，我启动5.2.2版本SlopeCraft时有概率会弹出以下窗口 ![image](https://private-user-images.githubusercontent.com/49829769/330190897-4f7c5a7e-b6d1-495a-9c4d-dbf4ac13c995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTE2NzcsIm5iZiI6MTcxNTY1MTM3NywicGF0aCI6Ii80OTgyOTc2OS8zMzAxOTA4OTctNGY3YzVhN2UtYjZkMS00OTVhLTljNGQtZGJmNGFjMTNjOTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAxNDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNDdiMjlmYjY1NGFkOGM0NTMyYWE0YzRkZTAxYWQzOGI2OTU4NTI5NGM1Njc1Y2QxMjE3ZTIwOWYyYTE5MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2oKzO9TKqXG7PNpEw7UdlDEOAfHiGvOsTM8cx0ELb54) 日志如下： `{"message":"API rate limit exceeded for 125.227.83.26. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}` 老版本貌似没有这个问题

如果这个错误信息可参考，这是因为 GitHub API 的调用限制被触发了，目前没有什么直接的办法可以解决

**Comment by ToKiNoBug** [comment]
> > 顺便也补充下，我启动5.2.2版本SlopeCraft时有概率会弹出以下窗口 ![image](https://private-user-images.githubusercontent.com/49829769/330190897-4f7c5a7e-b6d1-495a-9c4d-dbf4ac13c995.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTE2NzcsIm5iZiI6MTcxNTY1MTM3NywicGF0aCI6Ii80OTgyOTc2OS8zMzAxOTA4OTctNGY3YzVhN2UtYjZkMS00OTVhLTljNGQtZGJmNGFjMTNjOTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAxNDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNDdiMjlmYjY1NGFkOGM0NTMyYWE0YzRkZTAxYWQzOGI2OTU4NTI5NGM1Njc1Y2QxMjE3ZTIwOWYyYTE5MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2oKzO9TKqXG7PNpEw7UdlDEOAfHiGvOsTM8cx0ELb54) 日志如下： `{"message":"API rate limit exceeded for 125.227.83.26. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}` 老版本貌似没有这个问题
> 
> 如果这个错误信息可参考，这是因为 GitHub API 的调用限制被触发了，目前没有什么直接的办法可以解决

确实没什么解决方法，但完全可以隐藏这个问题，现在我认为自动检查更新失败了就不弹窗是比较合理的。

**Comment by ToKiNoBug** [comment]
> 不过我发现了另一个问题：导出的平面示意图是使用方块的侧视图生成的，这导致侧视图和俯视图不同的方块的效果很奇怪。

倒不一定是侧视图，只是代表性的图案，方便用户能认出来每一个方块。不过那个诡异的、间隔一列的平面示意图确实是bug

**Comment by ToKiNoBug** [comment]
> > 不过我发现了另一个问题：导出的平面示意图是使用方块的侧视图生成的，这导致侧视图和俯视图不同的方块的效果很奇怪。

我当初是真没想到半砖的平面示意图会这么逆天……确实还是应该增加一个俯视图

**Comment by ToKiNoBug** [comment]
5.3.0已修复
