### ISSUE TITLE
[功能请求]: `地图画配置` 的 `方块列表` 中提供 `全选` & `全不选` & `反选` 等选项

### ISSUE THREAD

**Issue by Tinhone** [SlopeCraft/SlopeCraft#116]
### 请选择：

- [ ] 我正在着手增加这个功能

### 描述您想要的解决方案

如题，在 `地图画配置` 一栏的 `方块列表` 中提供 `全选` & `全不选` & `反选` 等选项，能够全选 & 全不选 & 反选基础颜色，以便操作。

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定没有人提交过与此功能请求相关的 issue

**Comment by ToKiNoBug** [comment]
> ### 请选择：
> 
>     * [ ]  我正在着手增加这个功能
> 
> 
> ### 描述您想要的解决方案
> 
> 如题，在 `地图画配置` 一栏的 `方块列表` 中提供 `全选` & `全不选` & `反选` 等选项，能够全选 & 全不选 & 反选基础颜色，以便操作。
> ### 描述您考虑过的替代方案
> 
> _No response_
> ### 还有其他的吗？
> 
> _No response_
> ### 请确认以下条款
> 
>     * [x]  我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定没有人提交过与此功能请求相关的 issue

可，我会实现这个功能
