### ISSUE TITLE
[Bug]: Linux版本找不到libboost_iostreams.so.1.74.0

### ISSUE THREAD

**Issue by DreamHelium** [SlopeCraft/SlopeCraft#117]
### Please choose if applies:

- [ ] I'm currently working on a fix.

### Issue Description

解压`SlopeCraft-5.2.2-Linux.tar.xz`后在`bin`里面运行`SlopeCraft`的时候会提示：
`./SlopeCraft: error while loading shared libraries: libboost_iostreams.so.1.74.0: cannot open shared object file: No such file or directory`

### Reproduction

运行`SlopeCraft`

### Relevant log output (if applicable)

```Shell
`ldd SlopeCraft | grep "not found"`:
`libboost_iostreams.so.1.74.0 => not found`

`ls /usr/lib64 | grep boost`:
`libboost_filesystem.so.1.85.0
libboost_iostreams.so.1.85.0
libboost_locale.so.1.85.0
libboost_thread.so.1.85.0`

说明唯有此库未找到但系统中有更新的版本
```

### Environment

- **Operating System**: openSUSE Tumbleweed 20240622
- **SlopeCraft Version**: 5.2.2

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/SlopeCraft/SlopeCraft/issues) and this has not been posted before
- [X] This is a bug report
- [X] This bug still exists

**Comment by DreamHelium** [comment]
`sudo cp /usr/lib64/libboost_iostreams.so.1.85.0 /usr/lib64/libboost_iostreams.so.1.74.0`后就能运行了，但是只能作为临时解决方案

**Comment by ToKiNoBug** [comment]
好吧，在ubuntu上编译的发布的时候没有带这些依赖，我觉得开源软件不需要在linux打包一堆动态库。我运行github actions重新编译一下应该好了，本地编译安装肯定也没有这个问题
