### ISSUE TITLE
[Bug]: 在预览材料表中，第13种材料的数量总是会远远超出实际的数量

### ISSUE THREAD

**Issue by Hoshub** [SlopeCraft/SlopeCraft#118]
### Please choose if applies:

- [ ] I'm currently working on a fix.

### Issue Description

每次在软件内导出材料表时，第13种材料的数量总是会远远超出实际的数量，这是一个很明显的bug。下面是两张导出的实例
![屏幕截图 2024-07-11 152614](https://github.com/SlopeCraft/SlopeCraft/assets/175292563/2f5b0ed4-2664-4b61-9d6d-3b69e29e0c56)
![屏幕截图 2024-07-11 152729](https://github.com/SlopeCraft/SlopeCraft/assets/175292563/ca15f2a3-62db-46cf-a322-988ca12dd85b)

### Reproduction

Bug复现方法：
1. 在“导入图像并转化”中随便添加一张图片，选定RGB+和抖动，并转化当前图像。
2. 在“导出”中选择“Litematica”，选择刚才转化的图片，先“预构建三维结构”，然后“预览材料表”。可以看到，在材料表中第13种材料的数量远远超出实际。

### Environment

- **Operating System**:Windows 11 家庭中文版 23H2
- **SlopeCraft Version**: 5.2.2

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/SlopeCraft/SlopeCraft/issues) and this has not been posted before
- [X] This is a bug report
- [X] This bug still exists

**Comment by ToKiNoBug** [comment]
我终于知道这是为什么了，这是个哭笑不得的bug：以前不支持材料表排序，因此直接根据材料表的行数确定每种方块一组的数量（水是第13行），支持排序之后忘了改这里。正在修这个bug

**Comment by ToKiNoBug** [comment]
5.3.0已修复
