### ISSUE TITLE
发现一个BUG

### ISSUE THREAD

**Issue by qiujunhan** [SlopeCraft/SlopeCraft#125]
似乎长条的方块太高导致生成的像素画少像素
![2024-12-04_22 46 04_4K](https://github.com/user-attachments/assets/da631afb-9106-44a9-85af-ec452078973f)

使用的图片
![concatenated_image](https://github.com/user-attachments/assets/5b0c1795-e898-4720-bc49-bb9777db10f5)
使用的设置
![image](https://github.com/user-attachments/assets/d0e2c09e-4565-4ef0-9ccd-81d40ccc6945)
![image](https://github.com/user-attachments/assets/580a78fc-582b-40c4-8ec6-8d914e4737da)

**Comment by Cubik65536** [comment]
issue 已转移，因为已经确认不是 BUG 我就直接 close 了

@Mifan-T 如果文档需要修改可以再在文档那边单独开 issue 记录所需工作
