### ISSUE TITLE
[Bug]: use modified PKGBUILD from aur failed to build

### ISSUE THREAD

**Issue by RealRoller233** [SlopeCraft/SlopeCraft#127]
### Please choose if applies:

- [X] I'm currently working on a fix.

### Issue Description

将aur的PKGBUILD中pkgver改为5.3.0,编译器换用gcc和g++编译失败
[PKGBUILD](https://gist.github.com/RealRoller233/99a4625e2069ee4d46b532ef34fb1913)
[build.log1](https://gist.github.com/RealRoller233/a35044155cdb973b432a05742207516d)
修改CMakeLists和linux.cpp之后报错[build.log2](https://gist.github.com/RealRoller233/7f060e166c4123803a5973fc602715a6)
后面我发现复现不了了，不知道为啥

### Reproduction

使用archlinux
git clone https://aur.archlinux.org/slopecraft.git
修改[PKGBUILD](https://gist.github.com/RealRoller233/5fc90b86794d90b94b3e09e78631d277)
makepkg -si 

### Environment

- **Operating System**:archlinux
- **SlopeCraft Version**:5.3.0

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/SlopeCraft/SlopeCraft/issues) and this has not been posted before
- [X] This is a bug report
- [X] This bug still exists

**Comment by Cubik65536** [comment]
所以你提交的 https://github.com/SlopeCraft/SlopeCraft/pull/128 是解决了这个问题吗？如果解决了可以把 issue close 了吗？

**Comment by RealRoller233** [comment]
> 所以你提交的 #128 是解决了这个问题吗？如果解决了可以把 issue close 了吗？

ok
