### ISSUE TITLE
软件界面翻译问题

### ISSUE THREAD

**Issue by K9wwh** [SlopeCraft/SlopeCraft#58]
### 我的操作
slopecraft软件初始界面 - ”导出为” 下方的 “WE原理图” 在简体中文选项中显示为 “WESchem”， 而在英文中显示为“WE原理图”

### 我认为应当发生的事情
在中文界面显示“WE原理图”，在英文界面中显示“WESchem”

### 实际上发生的事情
<img width="731" alt="1674357286076" src="https://user-images.githubusercontent.com/101035242/213898937-4bd97cab-e7c0-49b1-b4f0-4674de000f0a.png">
<img width="731" alt="1674357309965" src="https://user-images.githubusercontent.com/101035242/213898941-e22f9424-483b-4e68-ba8b-d020c83a2957.png">

### 其他
N/A

**Comment by ToKiNoBug** [comment]
谢谢，这个问题我着实没想到……下个版本就会改

**Comment by K9wwh** [comment]
我补充一下 还有这个界面也是同样的问题
![image](https://user-images.githubusercontent.com/101035242/214268940-9fc5a400-74ec-458c-b4b3-5406a935056b.png)
![image](https://user-images.githubusercontent.com/101035242/214268985-ce1af03b-e26a-47e9-aa2e-531a6b95860f.png)

**Comment by Cubik65536** [comment]
已确认修复，关闭 issue
