### ISSUE TITLE
[Bug]: 疑似预设方块列表有误导致多个功能无法使用

### ISSUE THREAD

**Issue by Mifan-T** [SlopeCraft/SlopeCraft#69]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

《因为bug过于有规律导致我想不出具体原因只能当成特性把规律写下来》

#### bug规律总结：

无论导入的图片、选择的版本和地图类型是什么，在"预设方块列表"中随意选择一个除"Custom"以外的预设后，都无法使用"转化为地图画"、"显示原画"、"测试方块列表"、"输出当前颜色表"功能（按钮为灰色），之后再选中"Custom"也无法恢复。
并且，如果地图画类型选择的是立体地图画（默认预设不含水），则按上文第一次随意选择预设时，右侧可用颜色种类会莫名其妙多出3种（不过这并不会影响功能无法正常使用:），并且，在使用下文中的解决方法后也会恢复正常。

#### 目前的手动解决方法（或许这也算是一种bug/特性？）：

第一种：在"游戏版本"中随意切换到高版本再切换回去，原先灰掉的按钮都会恢复正常[为什么是高版本？因为往低版本切换会自动取消勾选低版本没有的方块，而切换回高版本时又不会自动勾选回去，导致可用颜色减少(而且"预设方块列表"显示的预设不会变，有亿点点反人类，希望能改掉)]。
第二种：在“地图画类型”中来回切换一次类型就完事了，按钮全部恢复正常（这样切换水居然能自动勾选回去，真是神奇）
第三种：在"方块列表"界面内的 _滑动区_ 手动进行任意点选操作（点击已经选择的方块也行），这时"预设方块列表"会自动跳到"Custom"，所有按钮也恢复正常
_[注]：**滑动区** 是指下图中的部分_
![滑动区](https://user-images.githubusercontent.com/49829769/228094374-ea4350c1-c55d-48dd-a520-7e184b9c22b7.jpg)

### 重现

1. 启动SlopeCraft.exe
2. 点击"创建立体地图画"进入导入图片界面
3. 点击"导入图片"随意导入一张图片
4. 点击"下一步"进入设置地图画类型界面
5. 点击"下一步"直接进入设置方块列表界面
6. 点击"预设方块列表"中的"Cheap"
7. 点击"下一步"进入调整颜色界面
8. 观察到调整颜色界面中的"转化为地图画"、"显示原画"、顶部高级菜单中的"测试方块列表"、"输出当前颜色表"按钮变为不正常的灰色，结束

### 环境

我使用了两台Win10系统的电脑，均稳定复现

操作系统1：Windows 10 专业版 21H1
操作系统2：Windows 10 专业版 22H2
SlopeCraft 版本：均为 3.10.1

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by Mifan-T** [comment]
另外说一下，我不知道为什么在bug反馈模板中无法附加图片，有点不方便

**Comment by Cubik65536** [comment]
> 另外说一下，我不知道为什么在bug反馈模板中无法附加图片，有点不方便

@Mifan-T 你可以将图片放入回复中发送，模板的问题我会着手修复

**Comment by ToKiNoBug** [comment]
这个bug我已经复现出来了，而且目前最新的测试版也没有修复。这确实是方块列表的逻辑复杂，而且代码比较乱，我试着打个补丁修复一下吧

**Comment by ToKiNoBug** [comment]
不能按下Convert的bug已经修复，但颜色数量计算有错的bug还没找到原因。SlopeCraft 的界面逻辑已经挺乱的了，我尽量努力修复吧
