### ISSUE TITLE
[BETA]: 我在正式版发现了一些小bug，需要测试版验证其是否已被修复

### ISSUE THREAD

**Issue by Mifan-T** [SlopeCraft/SlopeCraft#73]
### “我确认："

- [X] 我希望试用 SlopeCraft 的测试版。
- [ ] 我希望试用 VisualCraft 的测试版。
- [X] 我明白测试版可能会有错误和不稳定。
- [X] 我愿意报告错误并提供反馈。

### 联系方式

电子邮件：<mifan_t@qq.com>

**Comment by ToKiNoBug** [comment]
已经发到你的邮箱里了，请查收

**Comment by ToKiNoBug** [comment]
> 已经发到你的邮箱里了，请查收

另外：测试版打开之后可能会有检查更新失败的情况，不考虑网络不通畅的原因，这是因为测试版还没有发布，软件检索不到主版本号为5的发布。正式发布之后就能检索到，就不会有这个bug。

**Comment by Mifan-T** [comment]
> > 已经发到你的邮箱里了，请查收
> 
> 另外：测试版打开之后可能会有检查更新失败的情况，不考虑网络不通畅的原因，这是因为测试版还没有发布，软件检索不到主版本号为5的发布。正式发布之后就能检索到，就不会有这个bug。

收到，正在开展测试
