### ISSUE TITLE
[Bug]: "测试方块列表"导出时报错

### ISSUE THREAD

**Issue by Mifan-T** [SlopeCraft/SlopeCraft#74]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

导出 **测试方块列表** 时，点击保存后弹出错误信息如下
![测试方块列表失败](https://user-images.githubusercontent.com/49829769/228424724-6b99a050-1295-4433-af29-b9be5985f04f.jpg)
经过测试，不论怎么操作（设置游戏版本、地图画类型等），保存后都会报错，但是文件实际成功被导出了，而且能正确加载到游戏里，并且导出的各版本列表都正常

- **也就是说，是一个无关紧要的报错**
- 正式版和测试版均能复现

### 重现

这里以正式版为例，测试版操作相同
1. 启动SlopeCraft.exe
2. 点击"创建立体地图画"进入导入图片界面
3. 点击"导入图片"随意导入一张图片
4. 点击高级菜单中的 **测试方块列表**
5. 选择保存路径和文件名，点击保存
6. 弹出错误信息，并且观察到刚才的列表已经导出，结束

### 环境

- **操作系统**：Windows 10 专业版 21H1
- **SlopeCraft 版本：**：3.10.1 / 5.0.0-dev-2023-03-29-10-35

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by ToKiNoBug** [comment]
怪哎，这是怎么回事

**Comment by ToKiNoBug** [comment]
这个bug已经修了，错误原因是：我大改了输出原理图的子项目之后，没有跟着修改这个功能的代码，忘了给它设置版本。这种情况下输出的结构方块文件还能被加载，有点奇妙

**Comment by Cubik65536** [comment]
已确认修复，关闭 issue
