### ISSUE TITLE
[Bug]: 多个指向url的按钮不起作用

### ISSUE THREAD

**Issue by Mifan-T** [SlopeCraft/SlopeCraft#75]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

下图框出的5个按钮按下后都没有任何反应
![联系作者-](https://user-images.githubusercontent.com/49829769/228686784-dd485014-5479-41b1-bf51-34605ba9d59b.jpg)![关于-联系作者](https://user-images.githubusercontent.com/49829769/228686793-a35564a7-8ccc-489e-902d-f60a90505f55.jpg)
按我的理解，这些按钮都是指向的url，就算网络不畅，浏览器也会启动并打开新的页面
但实际情况是，按下后一点反应都没有，什么也没有发生。
而且左侧选项卡和上方选项卡中有部分按钮重复，但有的能起作用，有的不起作用，令人疑惑

> - 我在两台电脑上都能稳定复现，基本可以排除网络问题
> - 正式版和测试均能复现

_bug太多啦，慢慢修吧（躺）_

### 重现

我认为这不需要举例

### 环境

- **操作系统**：Windows 10 专业版 21H1 / 22H2
- **SlopeCraft 版本：** 3.10.1 / 5.0.0-dev-2023-03-29-10-35
- **浏览器：** Chrome

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by ToKiNoBug** [comment]
感谢反馈，这个bug我也复现出来了，我看看是什么问题

**Comment by ToKiNoBug** [comment]
这个bug也修复了，我没加https://的前缀，Qt以为url是指向文件系统的东西了

**Comment by Cubik65536** [comment]
已确认修复，关闭 issue
