### ISSUE TITLE
[功能改进]: 图像预览框的改进建议

### ISSUE THREAD

**Issue by Mifan-T** [SlopeCraft/SlopeCraft#82]
### 描述

**有两处需要改进的地方**

**1. 差值**
目前的预览框显示图像时使用了差值，会模糊每个像素的边缘。这势必会对地图画的预估造成影响，尤其在低分辨率下特别明显。
建议是改为常值显示（eg：几乎所有图像编辑软件内都以常值显示图像）

_↓原图_
![QR](https://user-images.githubusercontent.com/49829769/231116986-63fa9456-3bfe-4e18-9b9e-057233fbb712.jpg)
_↓SlopeCraft中_
![QR-SC](https://user-images.githubusercontent.com/49829769/231119311-df5e434f-3238-4f68-a835-e05c967c3fba.jpg)
_↓游戏中（众所周知游戏中地图画是以常值显示的）_
![QR-game](https://user-images.githubusercontent.com/49829769/231118369-4b713877-abcb-4775-8657-d8ba984a0831.jpg)
**2.图像填充方式**
目前图像会默认填满整个预览框，如果导入的是长方形图像，在默认窗口下就会被拉伸，而且缩放窗口时也会改变图像的高宽比，这在一定程度上也会对地图画的预估造成影响。_（最重要的是窗口很难缩放出完美的原比例，强迫症难受啊啊啊）_ 
建议是图像大小自动适配窗口大小，避免被一起拉伸（eg：Microsoft 照片、PotPlayer）

_↓导入长方形图像，未缩放窗口_
![导入长方形图像](https://user-images.githubusercontent.com/49829769/231133016-9ab6fce0-ce35-4e2b-81e0-ecde33f4a7ce.jpg)

**Comment by ToKiNoBug** [comment]
ok，我会再试着改一改缩放和显示图片的行为，但不一定能成功，

**Comment by ToKiNoBug** [comment]
这两个行为都是qt内置的特性，我试过修改qlabel的行为和qgridlayout的设置，但确实没有实现一个满意的方案。我应该还会继续试试，但我可能在发布下一个版本之后再修复

**Comment by Mifan-T** [comment]
@ToKiNoBug 未来会有操作逻辑的改进计划吗？目前的操作逻辑并不是很直观

**Comment by ToKiNoBug** [comment]
> @ToKiNoBug 未来会有操作逻辑的改进计划吗？目前的操作逻辑并不是很直观

操作逻辑改起来就不太容易了，SlopeCraft 的界面设计的并不好，改逻辑等同于重写界面。

**Comment by Mifan-T** [comment]
> 操作逻辑改起来就不太容易了，SlopeCraft 的界面设计的并不好，改逻辑等同于重写界面。

唔，我这里指的就是界面的操作逻辑。我有办法在尽量只移动界面中各元素的前提下改善操作逻辑，这样工作量应该会轻很多吧？

**Comment by ToKiNoBug** [comment]
> > 操作逻辑改起来就不太容易了，SlopeCraft 的界面设计的并不好，改逻辑等同于重写界面。
> 
> 唔，我这里指的就是界面的操作逻辑。我有办法在尽量只移动界面中各元素的前提下改善操作逻辑，这样工作量应该会轻很多吧？

请讲一讲你的修改建议/方案

**Comment by Mifan-T** [comment]
> 请讲一讲你的修改建议/方案

ok，我会尽量整理出一系列可行方案，并单独发个issue以供参考。内容比较多，可能需要一段时间

**Comment by ToKiNoBug** [comment]
> > 请讲一讲你的修改建议/方案
> 
> ok，我会尽量整理出一系列可行方案，并单独发个issue以供参考。内容比较多，可能需要一段时间

谢谢，我很期待你的建议。另外对图像显示的方案也有了大致的思路，可以修改QLabel的缩放策略，实现你描述的效果

**Comment by ToKiNoBug** [comment]
我现在已经修改了缩放策略，你可以试试最新的测试版（从这个仓库的github action上找到最新的一个action，下载这次编译上传的artifacts

https://github.com/SlopeCraft/SlopeCraft/actions/runs/4717911228

**Comment by Mifan-T** [comment]
> 我现在已经修改了缩放策略，你可以试试最新的测试版（从这个仓库的github action上找到最新的一个action，下载这次编译上传的artifacts
> 
> https://github.com/SlopeCraft/SlopeCraft/actions/runs/4717911228

#### 经过测试，目前的缩放策略还有一些小问题：

#### 1. 在![导入图片](https://user-images.githubusercontent.com/49829769/232469888-a3c128d1-a73b-4e9e-a14e-5242fe6479b8.jpg)界面中，图像向右侧放大时会消耗过长的时间。
举个例子，下图从默认窗口切换到最大化时，放大图像消耗了约4.8s
![shizuku](https://user-images.githubusercontent.com/49829769/232467571-1cc46c77-1d4d-436a-b03f-76c00178f78b.jpg)

#### 2.在![调整颜色](https://user-images.githubusercontent.com/49829769/232469985-131ad27b-5742-4fb8-a113-51ee723fb24e.jpg)界面中，图像并没有居中显示，而是靠左显示。
_↓调整颜色界面_
![调整颜色中](https://user-images.githubusercontent.com/49829769/232471154-e80be2a2-f979-45b7-b926-18d622934c61.jpg)
_↓导入图片界面（对比用）_
![导入图片中](https://user-images.githubusercontent.com/49829769/232471302-33777528-890b-4271-89da-c0d0d43e6d66.jpg)

**Comment by ToKiNoBug** [comment]
> > 我现在已经修改了缩放策略，你可以试试最新的测试版（从这个仓库的github action上找到最新的一个action，下载这次编译上传的artifacts
> > https://github.com/SlopeCraft/SlopeCraft/actions/runs/4717911228
> 
> #### 经过测试，目前的缩放策略还有一些小问题：
> #### 1. 在![导入图片](https://user-images.githubusercontent.com/49829769/232469888-a3c128d1-a73b-4e9e-a14e-5242fe6479b8.jpg)界面中，图像向右侧放大时会消耗过长的时间。
> 
> 举个例子，下图从默认窗口切换到最大化时，放大图像消耗了约4.8s ![shizuku](https://user-images.githubusercontent.com/49829769/232467571-1cc46c77-1d4d-436a-b03f-76c00178f78b.jpg)
> #### 2.在![调整颜色](https://user-images.githubusercontent.com/49829769/232469985-131ad27b-5742-4fb8-a113-51ee723fb24e.jpg)界面中，图像并没有居中显示，而是靠左显示。
> 
> _↓调整颜色界面_ ![调整颜色中](https://user-images.githubusercontent.com/49829769/232471154-e80be2a2-f979-45b7-b926-18d622934c61.jpg) _↓导入图片界面（对比用）_ ![导入图片中](https://user-images.githubusercontent.com/49829769/232471302-33777528-890b-4271-89da-c0d0d43e6d66.jpg)

第二个问题已经修复了。

关于第一个问题，向右侧放大的时候，我没感觉到明显的卡顿，而是看到一个逐渐放大的过渡，在你的电脑上会引发卡顿吗？

**Comment by Mifan-T** [comment]
> 现在你说的第一个问题也修复了，可以在本仓库的actions里下载预览版试试

现在看起来不错。不过在`调整颜色`界面放大窗口时，图像依然有推动右侧边界框的现象。这不影响使用，如果有余力的话可以尝试修下

**Comment by ToKiNoBug** [comment]
> > 现在你说的第一个问题也修复了，可以在本仓库的actions里下载预览版试试
> 
> 现在看起来不错。不过在`调整颜色`界面 _缩小_ 窗口时，图像依然有推动右侧边界框的现象。这不影响使用，如果有余力的话可以尝试修下
> 
> *更正：是缩小窗口

奇怪，我复现不出来这个现象

**Comment by Mifan-T** [comment]
> 奇怪，我复现不出来这个现象

_↓like this_
![GIF](https://user-images.githubusercontent.com/49829769/232721855-927eda4a-9472-45da-9d8a-1150d12d69c5.gif)

**Comment by Mifan-T** [comment]
> 我还是重复不出来这个效果。要不试试github actions里最新的测试版？

我用最新的测试版(2adff84)仍能稳定复现。注意一下导入的是否为同一张图，正方形图片是无法复现的

另外，我在我的另一台电脑上无法打开V5.0及以上的SlopeCraft（包括稳定版），报错如下
![屏幕截图 2023-04-18 232911](https://user-images.githubusercontent.com/49829769/232833329-7762e073-4b97-48da-8789-9208bb429647.png)
操作系统：Windows 10 专业版 22H2

这使我无法验证这个问题是否是我的系统导致的

**Comment by ToKiNoBug** [comment]
> 

这个错误好像很经典，是一些系统dll没有被操作系统注册。Qt界面库肯定是要连接到操作系统dll的。网上有很多解决方案

**Comment by Mifan-T** [comment]
> 我还是重复不出来这个效果。要不试试github actions里最新的测试版？

我在Hyper-V虚拟机上仍能稳定复现，基本可以排除系统问题
环境：win10企业版LTSC 21H2/win10专业版 21H2

再次提醒：注意你导入的是否和我为同一张图、操作界面是否为“调整颜色”


_（Hyper-V真的好卡啊啊啊）_

**Comment by ToKiNoBug** [comment]
> 

这应该是因为计算机上缺了api set stub dll，也就是windows系统的api集，找不到api-ms-这一系列的dll。我不想在压缩包里打包一套VC运行库（也不应该这样）。可以试试安装一下vc运行库，或者在启动windows功能里，勾选.net

**Comment by Mifan-T** [comment]
> 这应该是因为计算机上缺了api set stub dll，也就是windows系统的api集，找不到api-ms-这一系列的dll。我不想在压缩包里打包一套VC运行库（也不应该这样）。可以试试安装一下vc运行库，或者在启动windows功能里，勾选.net

我安装了各版本的VC运行库也没法解决问题，我觉得这应该是之前发生的硬盘故障导致的，现在系统发生了很多不该发生的问题，不过我懒得修了。之后如果有必要，我会在虚拟机上进行测试

**Comment by ToKiNoBug** [comment]
> 我安装了各版本的VC运行库也没法解决问题，我觉得这应该是之前发生的硬盘故障导致的，现在系统发生了很多不该发生的问题，不过我懒得修了。之后如果有必要，我会在虚拟机上进行测试

现在破案了，虚拟机很可能不支持avx和avx2指令集，这导致SlopeCraftL.dll初始化全局变量的时候失败（遇到非法指令，Eigen使用了avx指令来给矩阵填0），估计DllMain会返回一个错误，然后windows系统认为是dll初始化失败，就报0xc0000142错误。至少这是我自己遇到的情况。

如果有人在物理机上遇上了同样的问题，那很可能是cpu太老，不支持avx和avx2。

我写代码的时候就基本没有考虑支持老cpu，我觉得avx2指令集应该已经在个人电脑上普及了。我不认为这是个代码错误，纯粹就是电脑运行环境的问题。

**Comment by Mifan-T** [comment]
> 现在破案了，虚拟机很可能不支持avx和avx2指令集，这导致SlopeCraftL.dll初始化全局变量的时候失败（遇到非法指令，Eigen使用了avx指令来给矩阵填0），估计DllMain会返回一个错误，然后windows系统认为是dll初始化失败，就报0xc0000142错误。至少这是我自己遇到的情况。
> 
> 如果有人在物理机上遇上了同样的问题，那很可能是cpu太老，不支持avx和avx2。
> 
> 我写代码的时候就基本没有考虑支持老cpu，我觉得avx2指令集应该已经在个人电脑上普及了。我不认为这是个代码错误，纯粹就是电脑运行环境的问题。

我看了下，的确没有avx2指令集
向下兼容还是有必要的，因为你永远想不到MC玩家都在用什么奇怪的设备 ┐(ﾟ～ﾟ)┌ 
![屏幕截图 2023-05-13 221027](https://github.com/SlopeCraft/SlopeCraft/assets/49829769/ac3a9ccf-97a5-45ac-8a1c-7edd391f98b1)
_↑甚至还有光驱_

**Comment by Cubik65536** [comment]
> > 我安装了各版本的VC运行库也没法解决问题，我觉得这应该是之前发生的硬盘故障导致的，现在系统发生了很多不该发生的问题，不过我懒得修了。之后如果有必要，我会在虚拟机上进行测试
> 
> 现在破案了，虚拟机很可能不支持avx和avx2指令集，这导致SlopeCraftL.dll初始化全局变量的时候失败（遇到非法指令，Eigen使用了avx指令来给矩阵填0），估计DllMain会返回一个错误，然后windows系统认为是dll初始化失败，就报0xc0000142错误。至少这是我自己遇到的情况。
> 
> 如果有人在物理机上遇上了同样的问题，那很可能是cpu太老，不支持avx和avx2。
> 
> 我写代码的时候就基本没有考虑支持老cpu，我觉得avx2指令集应该已经在个人电脑上普及了。我不认为这是个代码错误，纯粹就是电脑运行环境的问题。

说到 avx 指令集，要提醒一下关于 Apple Silicon (M1/M2) 系列的兼容性，这类设备也对 avx 没有支持（转译是做不到转译指令集命令的）

我记得我们在 QQ 里提到过关闭向量化的话题？

**Comment by ToKiNoBug** [comment]
> 说到 avx 指令集，要提醒一下关于 Apple Silicon (M1/M2) 系列的兼容性，这类设备也对 avx 没有支持（转译是做不到转译指令集命令的）
> 
> 我记得我们在 QQ 里提到过关闭向量化的话题？

理论上我加了宏来控制是否使用avx，但没考虑过是否编译通过。目前这部分代码牵扯到一个内存写过界的漏洞，所以暂时没能修复。这个漏洞只是暂时被掩盖了，但我准备顺带着彻底修好

**Comment by ToKiNoBug** [comment]
> 我看了下，的确没有avx2指令集 向下兼容还是有必要的，因为你永远想不到MC玩家都在用什么奇怪的设备 ┐(ﾟ～ﾟ)┌ 

我会试着提供不带avx的版本，不过我觉得向下兼容也得有个极限，比如不考虑win7（这个真的很麻烦），不考虑32位（这个真的做不到）
