### ISSUE TITLE
[功能请求]: 优化 vccl 在 macOS 上的打包逻辑

### ISSUE THREAD

**Issue by Cubik65536** [SlopeCraft/SlopeCraft#84]
### 请选择：

- [ ] 我正在着手增加这个功能

### 描述您想要的解决方案

在 macOS 环境下，默认情况下，vccl 在编译过后会被打包成 `.app` 形式的 macOS 可执行文件。但是，由于 vccl 是命令行程序，这一步是不必要的，甚至会因此增加麻烦。但由于一些原因，我们又需要对其进行 deployqt 操作。我们或许需要找到一个方法在其被打包并部署完所需 Framework 后重新展开成一个命令行程序形式。

### 还有其他的吗？

目前的路径结构（被 `** **` 包括的文件/路径是我们需要在展开后保留的路径）

```
install
|-- vccl.app/Contents
	|-- **Frameworks**
	|-- Info.plist
	|-- **MacOS**
		|-- **Blocks_VCL (材质与方块数据文件路径)**
		|-- **vccl (可执行二进制，软连接到 vccl-5.0.0)**
		|-- **vccl-5.0.0 (可执行二进制)**
		|-- **vccl-config.json (配置文件)**
	|-- PlugIns
	|-- Resources
```

为了展开，我们需要将 `Frameworks` 与 `MacOS` 文件夹放置到安装路径下，并将 `MacOS` 更名为 `vccl`，结构如下：

```
install
|-- **Frameworks**
|-- **vccl (从 `MacOS` 更名而来)**
	|-- **Blocks_VCL (材质与方块数据文件路径)**
	|-- **vccl (可执行二进制，软连接到 vccl-5.0.0)**
	|-- **vccl-5.0.0 (可执行二进制)**
	|-- **vccl-config.json (配置文件)**
```

完成后，用户可以通过执行 `.../vccl/vccl` 来使用 vccl 程序

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定没有人提交过与此功能请求相关的 issue

**Comment by ToKiNoBug** [comment]
如果给`${CMAKE_INSTALL_PREFIX}/vccl.app/MacOS/vccl`创建一个软连接，就是`${CMAKE_INSTALL_PREFIX}/vccl`，这样如何？

**Comment by Cubik65536** [comment]
> 如果给`${CMAKE_INSTALL_PREFIX}/vccl.app/MacOS/vccl`创建一个软连接，就是`${CMAKE_INSTALL_PREFIX}/vccl`，这样如何？

可以，在不影响 app bundle 本身的情况下，这就是最好的方案，我觉得也是目前最好的方案了 /cc @ToKiNoBug

**Comment by ToKiNoBug** [comment]
> 

我不建议改vccl.app的名字。我不清楚能不能换掉.app后缀，而且我很不建议用-lib这个后缀，它有着库的含义，但vccl是个bundle。我会在文档里明确注明vccl.app和vccl符号连接的关系

**Comment by Cubik65536** [comment]
> > 
> 
> 我不建议改vccl.app的名字。我不清楚能不能换掉.app后缀，而且我很不建议用-lib这个后缀，它有着库的含义，但vccl是个bundle。我会在文档里明确注明vccl.app和vccl符号连接的关系

我们需要的只有链接到里面的二进制和相对路径正确的 frameworks 文件夹，所以我现在是将 bundle 视为普通文件夹处理的，现在继续使用 app 后缀误导性只会更高

正如我描述中说的，我们不仅不需要这个 bundle，现在麻烦就是因为他会被用户（以及系统）当作 bundle，我们只需要它被当做一个普通的存放二进制和其他文件的路径

@ToKiNoBug

**Comment by Cubik65536** [comment]
而且如果你认为 bundle 有什么特殊性的话，那它也只是一个有着固定文件结构的文件夹，以及通过加一个后缀用户可以双击打开而已。我们目前不需要任何属于这个 bundle 的特性，我说到的要保持相对路径也只是因为 deployqt 后二进制不会去其他地方搜索他需要的链接库

**Comment by Cubik65536** [comment]
综上：

1. 我们可以换掉 app 后缀，因为我们只需要将其当做一个普通路径。实际上我的最佳方案是把 app 里面的挪出来，更证明了其实我们甚至不需要这个文件夹
2. 正如你不希望有 lib 后缀一样，我也不希望它有任何方式暗示这个 bundle/文件夹 可以被直接执行 —- 用户不总是看文档

**Comment by Cubik65536** [comment]
close by https://github.com/SlopeCraft/SlopeCraft/tree/v5.0.1
