### ISSUE TITLE
[功能请求]: 建议在选择方块少于4种时阻止用户点击而非弹出错误导致直接关闭

### ISSUE THREAD

**Issue by huangguacucumber** [SlopeCraft/SlopeCraft#87]
### 请选择：

- [ ] 我正在着手增加这个功能

### 描述您想要的解决方案

建议在选择方块少于4种时阻止用户点击而非弹出错误导致直接关闭
如果直接关闭需要用户重新取消选择，更为麻烦
此外如果能添加保存材料分组功能就更好了，不用每次打开重新选择

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定没有人提交过与此功能请求相关的 issue

**Comment by ToKiNoBug** [comment]
> 此外如果能添加保存材料分组功能就更好了，不用每次打开重新选择

其实有这个功能，只是不太好找，在高级->方块列表预设->保存/导入预设里。目前在大改界面，我会让这个功能放在更明显的位置

**Comment by ToKiNoBug** [comment]
> 建议在选择方块少于4种时阻止用户点击而非弹出错误导致直接关闭

你希望的阻止用户点击，具体是什么样的？把剩下的“启用”按钮变成灰色来锁死它们？还是用户试图取消勾选的时候，自动勾选回去？

**Comment by ToKiNoBug** [comment]
啊对了，我还想问，你说的是这个项目里的哪个软件？SlopeCraft 还是 VisualCraft？

**Comment by Mifan-T** [comment]
> 啊对了，我还想问，你说的是这个项目里的哪个软件？SlopeCraft 还是 VisualCraft？

应该是SlopeCraft，已复现，报错如下
![image](https://user-images.githubusercontent.com/49829769/235301108-792bc37d-bacb-4286-84e7-d50f73fc1830.png)
关闭错误信息后SlopeCraft退出

**Comment by ToKiNoBug** [comment]
> > 啊对了，我还想问，你说的是这个项目里的哪个软件？SlopeCraft 还是 VisualCraft？
> 
> 应该是SlopeCraft，已复现，报错如下 ![image](https://user-images.githubusercontent.com/49829769/235301108-792bc37d-bacb-4286-84e7-d50f73fc1830.png) 关闭错误信息后SlopeCraft退出

是这样子啊。这是内核报错，所以会直接崩溃。当时这么处理是因为界面逻辑已经相当混乱，不敢再加新特性了，所以用了这个偷懒的方案。现在正好可以趁着大改的机会重写一下。

还是请你描述一下，你希望的“阻止用户点击”，具体是什么样的？

**Comment by Mifan-T** [comment]
> 还是请你描述一下，你希望的“阻止用户点击”，具体是什么样的？

（这问题比较复杂，我帮他回答吧）
我觉得简单地阻止用户点击并不能解决问题。
因为这个报错是因为地图色<4，并非基色过少，这意味着纯文件地图画最少能选择一个基色（1*4）（透明色必选，不会报错），而平面地图画最少能选择四个基色。所以在 `纯文件地图画`下不会崩溃的配置切换到 `平面地图画`可能会崩溃，另外加载的预设也可以绕开阻止点击。

其实最好的解决方法是防止此处和后续操作的崩溃（报错倒是可以有）
