### ISSUE TITLE
[功能请求]: 连接相邻的蘑菇柄

### ISSUE THREAD

**Issue by Cassy-Lee** [SlopeCraft/SlopeCraft#88]
### 请选择：

- [ ] 我正在着手增加这个功能

### 描述您想要的解决方案

对每一个蘑菇柄处理各个方向的连接

### 描述您考虑过的替代方案

在生成结构时阻止蘑菇柄生成在相邻的位置或生成后进行替换

### 还有其他的吗？

生成的投影文件中相邻的蘑菇方块没有相连，导致实装后出现“状态错误”（强迫症难受）

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定没有人提交过与此功能请求相关的 issue

**Comment by ToKiNoBug** [comment]
> ### 请选择：
> * [ ]  我正在着手增加这个功能
> 
> ### 描述您想要的解决方案
> 对每一个蘑菇柄处理各个方向的连接
> 
> ### 描述您考虑过的替代方案
> 在生成结构时阻止蘑菇柄生成在相邻的位置或生成后进行替换
> 
> ### 还有其他的吗？
> 生成的投影文件中相邻的蘑菇方块没有相连，导致实装后出现“状态错误”（强迫症难受）
> 
> ### 请确认以下条款
> * [x]  我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定没有人提交过与此功能请求相关的 issue

这个功能我其实想过，但偷懒没有实现。既然有人反馈了，我会试着实现一下的

**Comment by Cassy-Lee** [comment]
> 

提供一个思路，或许可以对所有可更新的方块模拟一次更新？批量弄可能比较方便，比如从yarn拿到所有材料的反混淆源码，筛选接受NC更新（Neighbor Change）的方块，查看原版如何处理邻接方块更新

**Comment by Cassy-Lee** [comment]
顺便可以拿到所有方块的默认状态

**Comment by ToKiNoBug** [comment]
> > 
> 
> 提供一个思路，或许可以对所有可更新的方块模拟一次更新？批量弄可能比较方便，比如从yarn拿到所有材料的反混淆源码，筛选接受NC更新（Neighbor Change）的方块，查看原版如何处理邻接方块更新

我现在的想法就是遍历整个三维结构，搜索周围属于蘑菇类型的方块，改方块id就行。
