### ISSUE TITLE
[Bug]: 0xc0000142

### ISSUE THREAD

**Issue by Dasupergrasskakjd** [SlopeCraft/SlopeCraft#89]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

運行SlopeCraft.exe時出現0xc0000142錯誤

### 重现

下載Release5.0.1版本
運行
出現錯誤

### 环境

- **操作系统**：Windows 10 21H2
- **SlopeCraft 版本：**：5.0.1

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by ToKiNoBug** [comment]
我可以推测出诱因是从qt6.1.0升级到了qt6.4.0，但目前我不知道更详细的原因。我搜了很多关于这个错误码的情况，但全都是含糊不清的描述，只知道是“有问题”，可能是语言和地区设置“有问题”，也可能是vc运行库“有问题”，但就是不知道什么问题，这真的很恶心。

我自己的系统上无法复现这个bug，不过我找到了一个可以检查系统环境的方法：以管理员权限启动一个cmd窗口，运行：`sfc /scannow`，这个命令好像是在扫描系统。请把这条命令输出的信息发出来。

**Comment by Dasupergrasskakjd** [comment]
C:\Windows\system32>sfc /scannow

正在開始系統掃描。這將需要一些時間。

開始系統掃描的驗證階段。
驗證 100% 完成。

Windows 資源保護找不到任何完整性違規。

**Comment by ToKiNoBug** [comment]
刚才我建了个win10虚拟机，终于复现出来这个bug了

**Comment by Dasupergrasskakjd** [comment]
有辦法解決嗎?

**Comment by ToKiNoBug** [comment]
> 有辦法解決嗎?

我再试试换一个win10编译出来的qt吧

**Comment by ToKiNoBug** [comment]
> 有辦法解決嗎?

我好像找到一个SlopeCraft启动失败的原因：在虚拟机里运行的时候，报了一个“非法指令集”的错误（vxorps，是avx），因为SlopeCraft用了avx和avx2，虚拟机好像不支持这些指令。我觉得这两个指令集应该非常普及了，所以放心大胆的直接用。

我想知道你的cpu型号，判断是不是因为没有avx指令导致的问题。如果是这个问题，我可以在编译的时候禁用avx，这样就能运行了。

**Comment by Dasupergrasskakjd** [comment]
Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz   2.20 GHz

**Comment by ToKiNoBug** [comment]
> Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz 2.20 GHz

我查了一下，这个cpu确实是比较老的了，支持avx但不支持avx2，而slopecraft是直接用了avx2。简单来说，因为cpu太旧，所以运行不了。

技术上我确实可以降低cpu要求，但修改代码很需要时间。最好的办法还是换一台稍微新一点的电脑。
