### ISSUE TITLE
[Bug]: VisualCraft 功能 `设置可用的方块` 出现问题

### ISSUE THREAD

**Issue by Tinhone** [SlopeCraft/SlopeCraft#90]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

当我启动软件后首次点击 `设置可用的方块` 时，会发生 `方块列表` 中自定义设置被重置的情况，并且我未看到错误信息

预期行为：当我启动软件后首次点击 `设置可用的方块` 时，应该不会发生 `方块列表` 中自定义设置被重置的情况

### 重现

1. 从 Release 下载应用
2. 设置 `基础属性` 并点击 `加载资源`
3. 设置 `方块列表` 并点击 `设置可用的方块`
4. 看到错误

### 环境

- **操作系统**：Windows 10 21H2
- **SlopeCraft 版本：**：5.0.1
- **VisualCraft版本：**：5.0.1

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by Tinhone** [comment]
点击 `加载资源` 两次以后再设置 `方块列表` 并点击 `设置可用的方块`，不会出现此问题

**Comment by Tinhone** [comment]
> 点击 `加载资源` 两次以后再设置 `方块列表` 并点击 `设置可用的方块`，不会出现此问题

按此方法设置，在生成 litematica 文件时，软件遇到致命错误后闪退
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/348b8346-3372-4b60-9115-0a9caa065ec1)

**Comment by Tinhone** [comment]
我采用多次点击 `设置可用的方块` 以缓解该问题，但在生成 litematica 文件时，软件会遇到致命错误后闪退，未找到日志输出
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/348b8346-3372-4b60-9115-0a9caa065ec1)

**Comment by ToKiNoBug** [comment]
你描述的第一个问题已经修复，你可以在[github actions](https://github.com/SlopeCraft/SlopeCraft/actions)的最新的工作流里下载测试版（大概需要等10分钟才能编译出来）

**Comment by ToKiNoBug** [comment]
> 我采用多次点击 `设置可用的方块` 以缓解该问题，但在生成 litematica 文件时，软件会遇到致命错误后闪退，未找到日志输出 ![图片](https://user-images.githubusercontent.com/81268244/241583629-348b8346-3372-4b60-9115-0a9caa065ec1.png)

这个问题有详细的复现方法吗？我试不出来

**Comment by Tinhone** [comment]
> > 我采用多次点击 `设置可用的方块` 以缓解该问题，但在生成 litematica 文件时，软件会遇到致命错误后闪退，未找到日志输出 ![图片](https://user-images.githubusercontent.com/81268244/241583629-348b8346-3372-4b60-9115-0a9caa065ec1.png)
> 
> 这个问题有详细的复现方法吗？我试不出来

1. 启动软件（5.0.1）
2. 设置 `基础属性`，使 `最大厚度` 为 3
3. 点击 `加载资源`
4. 设置 `方块列表`，使 1 个方块为禁用状态
5. 点击 `设置可用的方块`
6. 设置 `方块列表`，使 15-20 个方块为禁用状态
7. 点击 `设置可用的方块`
8. 设置 `选择图片`，使 `调色算法` 为 `RGB+`，开启 `抖动`，添加一张大小大约为 280w150h 的图片
9. 设置 `导出`，使 `导出类型` 为 `litematic投影`，同时设置 `导出位置`
10. 设置 `导出选项`，使 `投影名称（非文件名）` 包含中文、英文、数字，`区域名称` 为 01
11. 点击 `开始执行`

进度条前进到 50% 的时候，软件会未响应，然后崩溃
或许可以在测试版内添加一个打印日志功能，固定生成在 log 文件夹，这或许可以方便错误排查

**Comment by Tinhone** [comment]
SlopeCraft-dev-4047de8-Debug-None-vec=false-windows-7z 按上面方法可复现
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/68fc57d5-4038-46ae-aa08-2f4e02759ad0)

**Comment by ToKiNoBug** [comment]
我用你指定的测试版试了几次，复现不出来……能不能把你测试用的图像发一下？

**Comment by Tinhone** [comment]
![天和核心舱-长征5号B](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/6af8596c-1c57-46c6-81ac-699b34b59e71)
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/4f7528fa-fcf6-489b-84d7-552dc593e179)
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/de530f37-2f4f-4952-aefe-ba804bc03eed)
![图片](https://github.com/SlopeCraft/SlopeCraft/assets/81268244/c8317c09-ac18-4938-a4d0-566e279ce9d0)

**Comment by ToKiNoBug** [comment]
我复现出bug，并且知道原因了

**Comment by ToKiNoBug** [comment]
这确实是个相当隐蔽的bug，现在已经修复了。你同样可以在github actions里下载测试版。

**Comment by ToKiNoBug** [comment]
>  或许可以在测试版内添加一个打印日志功能，固定生成在 log 文件夹，这或许可以方便错误排查

其实软件是有一套报错系统的，只是不能在多线程环境里正常工作……

**Comment by Tinhone** [comment]
测试版功能运行正常，作者大大辛苦了🌹
