### ISSUE TITLE
[功能请求]: 快速导出&导入 VisualCraft `方块列表` 栏中方块启用设置

### ISSUE THREAD

**Issue by Tinhone** [SlopeCraft/SlopeCraft#91]
### 请选择：

- [ ] 我正在着手增加这个功能

### 描述您想要的解决方案

如题，希望在 `快捷键` 一侧新添加 `导出设置` `导入设置` 两个按钮

期望在点击 `导出设置` 按钮后执行导出方块启用设置文件操作

期望在点击 `导入设置` 按钮后执行导入方块启用设置文件操作

期望导出方块启用设置文件操作可供用户自由选择保存路径，可供用户设置默认保存路径

期望导入方块启用设置文件操作检查文件是否兼容 `基础属性` 中设置，若否则提示无法导入，不强制退出软件

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定没有人提交过与此功能请求相关的 issue

**Comment by ToKiNoBug** [comment]
这个功能可以加，不过你想要导出的设置，是仅仅包括所有方块的启用/禁用状态，还是包含界面其他设置？

**Comment by Tinhone** [comment]
> 这个功能可以加，不过你想要导出的设置，是仅仅包括所有方块的勾选状态，还是包含界面其他设置？

这个 issue 的期望是仅包含方块勾选状态

**Comment by ToKiNoBug** [comment]
ok，我会加入这个功能。
