### ISSUE TITLE
会继续更新1.20的Release吗

### ISSUE THREAD

**Issue by kohaku-2434** [SlopeCraft/SlopeCraft#92]
### 请选择：

- [ ] 我正在着手增加这个功能

### 描述您想要的解决方案

我感觉两种主要建材竹子竹板和樱花的出现会相当影响到今后地图画的构成，所以如果还会继续更新的话，想问问大概什么时候能放出？如果不会的话我就用1.19的开始做了，辛苦:D

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定没有人提交过与此功能请求相关的 issue

**Comment by ToKiNoBug** [comment]
我会继续更新，也许需要一周时间。

这些新方块好像依旧没有带来新的地图基色颜色，所以对SlopeCraft没什么影响，但对VisualCraft有影响。

**Comment by ToKiNoBug** [comment]
我已经跟进了1.20，给SlopeCraft和VisualCraft增加了新方块，但还没发布，你可以在本仓库的github actions里下载到测试版
