### ISSUE TITLE
[Bug]: VisualCraft启动时弹窗“设置GPU设备失败。，平台序号为0，设备序号为0”

### ISSUE THREAD

**Issue by kohaku-2434** [SlopeCraft/SlopeCraft#93]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

双击VisualCraft.exe时提示标题所示内容弹窗，然后给了ignore和close两个选项，我看了VC的使用说明网站页和常见问题都没有提示这个是如何解决的。

### 重现

默认下载Release5.0.1，文件夹内布局未进行任何更改，运行VisualCraft即提示如上所说的问题。

### 环境

- **操作系统**：Win10
- **SlopeCraft 版本**：5.0.1
- **显卡**：RTX 2060桌面显卡
- **CPU**：i5-10400F
- **内存**：32GB，运行时空闲24GB

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by ToKiNoBug** [comment]
你可能没有安装opencl，或者装的有问题。也有可能是你的环境没问题，但我写的代码没有在20系显卡上测试过。VisualCraft 默认使用第一个平台的第一个显卡计算，所以会出现这个报错。你可以点ignore，然后选用cpu或者核显计算。

**Comment by ToKiNoBug** [comment]
这个Bug已经在最新的更新中修复（https://github.com/SlopeCraft/SlopeCraft/release/latest
