### ISSUE TITLE
[其他]: 项目池不能覆盖图片

### ISSUE THREAD

**Issue by eserll** [SlopeCraft/SlopeCraft#96]
### 描述

在导入图片并转化里会提示透明像素处理策略
设置完后需要重新导入图片生效这个步骤，但是没有覆盖原先图片文件的选项，只有在项目池添加和删除图片
这样就没办法让设置生效了

所以大概可以把设置透明像素这个按钮在这个步骤里改回来，而且放一个默认设置的选项在高级选项里

**Comment by Mifan-T** [comment]
我测试了下，导入图片时确认转换策略后，处理是会立即生效的，只是描述可能忘了改
至于没法覆盖原图片的问题......这确实有待解决
@ToKiNoBug

**Comment by ToKiNoBug** [comment]
> 我测试了下，导入图片时确认转换策略后，处理是会立即生效的，只是描述可能忘了改 至于没法覆盖原图片的问题......这确实有待解决 @ToKiNoBug

emmmmm我确实是直接把旧的覆盖图片窗口直接拿来用了，我会修正这个错误。至于覆盖原图，好像不是很必要？完全可以删掉一个图，然后再导入一个

**Comment by Mifan-T** [comment]
> emmmmm我确实是直接把旧的覆盖图片窗口直接拿来用了，我会修正这个错误。至于覆盖原图，好像不是很必要？完全可以删掉一个图，然后再导入一个

覆盖原图倒是更符合逻辑一些，如果方便就加上吧。
其实蛮多地方都有待优化的，我倒是有用C#重写GUI的想法，只是目前还在学，可能要等半年:）

**Comment by ToKiNoBug** [comment]
这个功能已经在最新的更新中修复（https://github.com/SlopeCraft/SlopeCraft/release/latest
