### ISSUE TITLE
[Bug]: SlopeCraft 5.2.0 抖动转化有透明像素的图片崩溃

### ISSUE THREAD

**Issue by Leo0258** [SlopeCraft/SlopeCraft#99]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

添加格式为PNG（像素128x128）带有透明背景的图片，选中图片，选择转换算法RBG+，勾选[抖动]，点击[转化当前图片]后 SlopeCraft崩溃退出。如果图片不带有透明像素，则转化正常。

### 重现

1.添加格式为PNG（像素128x128）带有透明背景的图片
2.选中图片，选择转换算法RBG+
3.勾选[抖动]
4.点击[转化当前图片]
5.问题出现

### 环境

- **操作系统**：Windows 10 专业版 22H2
- **SlopeCraft 版本：**：5.2.0

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/SlopeCraft/SlopeCraft/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在

**Comment by ToKiNoBug** [comment]
我无法复现这个bug，请提供导致崩溃的图片和详细的透明像素处理策略

**Comment by wpcwzy** [comment]
我使用附件中的图像复现成功了，具体操作如下：
打开软件，单击导入图像并转化，添加该图片，替换为空气且背景色纯白，选中图像并开启抖动，转化当前图片，程序freeze，此时进度条100%，标题栏显示正在匹配颜色
![test](https://github.com/SlopeCraft/SlopeCraft/assets/16263217/ab9ee216-3105-409c-b65e-a3631ed12db9)

**Comment by wpcwzy** [comment]
用windbg attach了一下，捕捉到了一下exception
![image](https://github.com/SlopeCraft/SlopeCraft/assets/16263217/2a945547-5550-45fe-9646-bf4f0db8208a)

**Comment by wpcwzy** [comment]
下载了action里最新的debug版本又调试了一下，发现以下现象，当添加的png带透明度时，不管选择替换为背景色或空气，按下确定都会抛出c0000374越界异常（详情见附件图片），而如果导入的png不带透明度则一切正常，推测在导入图片的时候就已经出现越界错误了
![image](https://github.com/SlopeCraft/SlopeCraft/assets/16263217/97ea217c-555c-405e-ad7f-58bbb3c25e22)

**Comment by wpcwzy** [comment]
个人感觉问题出在这里？
![image](https://github.com/SlopeCraft/SlopeCraft/assets/16263217/f5862283-98cb-48a9-8724-63e6441ff01b)

**Comment by ToKiNoBug** [comment]
> 我使用附件中的图像复现成功了

谢谢，我用你提供的图片复现出来了，之前忙着比赛顾不上，现在已经在想办法修复了。我大概知道怎么回事，因为我改动过抖动的代码

**Comment by Leo0258** [comment]
感谢两位，辛苦了

**Comment by ToKiNoBug** [comment]
现在已经修复了崩溃的问题，但又出现了勾选抖动后，无法预览地图画材料表的问题。可以先从github actions里下载预览版。

GitHub actions里总是会编译出很多个预览版，推荐的下载链接：https://github.com/SlopeCraft/SlopeCraft/suites/16828276851/artifacts/961098474

**Comment by ToKiNoBug** [comment]
已经修复，请查看最新的release：https://github.com/SlopeCraft/SlopeCraft/releases/tag/v5.2.1
